### ISSUE TITLE
req.checkBody(...).optional(...).isDate is not a function

### ISSUE THREAD

**Issue by webchaussette** [mdn/express-locallibrary-tutorial#10]
Hi, I'm trying to learn Express framework by doing your tutorial ( https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms ) and encounter a problem. Whenever I submit a form that uses .isDate() validator (from express-validator module), I get the following error:

```
TypeError: req.checkBody(...).optional(...).isDate is not a function
    at exports.author_create_post (/Users/w/webhome/node/express-locallibrary-tutorial/controllers/authorController.js:50:83)
```

The only differences between my code and mdn's code are the dependencies versions of some modules:
```
"dependencies": {
    [...],
    "express": "~4.15.5",
    "express-validator": "^4.2.1",
    [...]
  },
```
in my package.json but
```
"dependencies": {
    [...],
    "express": "~4.14.0,
    "express-validator": "^3.0.0",
    [...]
  },
```
in mdn's package.json. The modules have been added by doing `npm install <module_name> --save`, as suggested in the tutorial.

We can reproduce the issue by cloning mdn's repository and changing the modules mentioned by more recent versions.

express-validator say their rewrite from 3.x to 4.x is backwards compatible
https://github.com/ctavan/express-validator/releases

Thank you very much for your help!

**Comment by hamishwillee** [comment]
@webchaussette The validator versions are very different - there was a big break in v4 - https://www.npmjs.com/package/express-validator#upgrade-notice
Generally speaking you should use the dependencies listed - who knows what might have changed since!

Looking at the validator code where isDate was defined you can see it no longer exists: https://github.com/chriso/validator.js
This should probably be updated to something like isISO8601(str)

@chrisdavidmills The validator has quite a big break. Not sure how much effort to properly test that nothing is broken and update to latest versions of components. Probably worth doing at some point though.

**Comment by webchaussette** [comment]
@hamishwillee thank you very much for answering this fast! I was able to make it work by doing the following changes:
<pre>
// Handle Author create on POST
exports.author_create_post = function(req, res, next) {

    req.checkBody('first_name', 'First name must be specified.').notEmpty(); //We won't force Alphanumeric, because people might have spaces.
    req.checkBody('family_name', 'Family name must be specified.').notEmpty();
    req.checkBody('family_name', 'Family name must be alphanumeric text.').isAlpha();
    req.checkBody('date_of_birth', 'Invalid date').optional({ checkFalsy: true }).isISO8601();
    req.checkBody('date_of_death', 'Invalid date').optional({ checkFalsy: true }).isISO8601();

    <strong>var errors = req.validationErrors();</strong>

    req.sanitize('first_name').escape();
    req.sanitize('family_name').escape();
    req.sanitize('first_name').trim();
    req.sanitize('family_name').trim();
    req.sanitize('date_of_birth').toDate();
    req.sanitize('date_of_death').toDate();

    var author = new Author(
      { first_name: req.body.first_name,
        family_name: req.body.family_name,
        date_of_birth: req.body.date_of_birth,
        date_of_death: req.body.date_of_death
       });
</pre>
Apparently, there's a bug in express-validator ( https://github.com/ctavan/express-validator/issues/431 ) thus the need to move `var errors = req.validationErrors();` before `req.sanitize()` functions are called.

On an unrelated note, shouldn't Family names be allowed to have spaces? (though for the purpose of this tutorial, it's nice to show another validator)  `req.checkBody('family_name', 'Family name must be alphanumeric text.').isAlpha();`

**Comment by hamishwillee** [comment]
Thanks @webchaussette for your fix. @chrisdavidmills As previously, we probably should do a broader review/update at some point.

> On an unrelated note, shouldn't Family names be allowed to have spaces? (though for the purpose of this tutorial, it's nice to show another validator) req.checkBody('family_name', 'Family name must be alphanumeric text.').isAlpha();

You could certainly argue this :-). If you wish to add support to the example and the documentation I am sure MDN would be happy to except the contribution.

**Comment by hamishwillee** [comment]
Thanks @webchaussette . This has now been updated in #17 .
I still have a little review work to do here, but it seems to all be running well.
