### ISSUE TITLE
Mongo DB connection using MongoClient instead of mongoose as per MongoDB docs.

### ISSUE THREAD

**Issue by minimallinux** [mdn/express-locallibrary-tutorial#11]
I altered my project package.json using docs on MongoDB site regarding MongoClient use.
I altered both app.js and populatedb.js with the following (removing mongoose references)
//Define MongoClient
   var MongoClient = require('mongodb').MongoClient
  , assert = require('assert');

//Set up connection
var dev_db_url = 'mongodb://user:pass@ds145275.mlab.com:45275/library'
var mongoDB = process.env.MONGODB_URI || dev_db_url;
MongoClient.connect(dev_db_url, function(err, db) {
  assert.equal(null, err);
  console.log("Connected correctly to server");
});

npm/node runs these with only a warning about promise and I get the success message to console, however populatedb does not populate my db at mlabs and there is no browser url for the display of the app at localhost
, I just get the success message, obviously there is something wrong with it somewhere, does anyone know where ?
Thanks

**Comment by hamishwillee** [comment]
[original code from here](https://github.com/mdn/express-locallibrary-tutorial/blob/master/app.js#L20):
```
//Set up mongoose connection
var mongoose = require('mongoose');
var dev_db_url = 'mongodb://cooluser:coolpassword@ds119748.mlab.com:19748/local_library'
var mongoDB = process.env.MONGODB_URI || dev_db_url;
mongoose.connect(mongoDB);
var db = mongoose.connection;
db.on('error', console.error.bind(console, 'MongoDB connection error:'));
```
And [poplulatedb.js is here](https://github.com/mdn/express-locallibrary-tutorial/blob/master/populatedb.js).

Just to eliminate the obvious, you did use a real user and pass right?

What is your command line to populatedb ?

What was the actual command line output?

**Comment by hamishwillee** [comment]
Closing as no response from poster
