### ISSUE TITLE
change var to const or let

### ISSUE THREAD

**Issue by RafaelGreen1** [mdn/express-locallibrary-tutorial#111]
there is an extensive use of **var**
it's better to change it **const** or **let** (depends on the situation)

**Comment by hamishwillee** [comment]
Yes :-).

The main reason I have chosen to stick with var for most of this, even though you're correct, is that most of the examples and documents from which this draws still use `var`. Similarly the express generator that we use for creating the basic app shell also uses var. 

For someone trying to come to grips with new material having everything consistent is more important than using the more recent language constructs. 

I'm closing this as "wontfix". However I do intend to update at some point - the trigger being when the express generator migrates to using const and let.
