### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by EriVelk** [mdn/express-locallibrary-tutorial#120]
In the template book_list.pug it does not allow me to access book.author.name

**Comment by hamishwillee** [comment]
Are you running exactly the code in this repository or your own version created from the tutorial? 

This means exactly what it says - probably you're passing in an empty book.author. You might want to check what you are passing in.

**Comment by EriVelk** [comment]
I am executing exactly the code from this repository.

**Comment by EriVelk** [comment]
I am very sorry for the inconvenience.

I found the problem.
Duplicate data in mongoDB and objectID of author in model book.js was not pointing to objectID of model author.js


Thanks for the attention.
