### ISSUE TITLE
 I have a problem with the book_form form

### ISSUE THREAD

**Issue by EriVelk** [mdn/express-locallibrary-tutorial#121]
When I press the Submit button the browser does not wait for the "localhost" and does nothing, it does not send me any error, it just stays in an infinite loop.

Thanks for reading

**Comment by hamishwillee** [comment]
@EriVelk Are you trying this with the code from THIS repository - or are you trying it with your own code created by following the tutorial?

On what OS, with what database?
Does this work for displaying data that has already been entered (i.e. do the "display" pages work)?

**Comment by EriVelk** [comment]
I am trying on my own code created from this example.

The OS I use is windows 10 and the database mongodb version 4.4.1

The views work fine and so do the other forms.

**Comment by EriVelk** [comment]
![image](https://user-images.githubusercontent.com/23425975/99738440-1b809180-2a90-11eb-8dd4-6a6690894181.png)

**Comment by EriVelk** [comment]
I am very sorry for the inconvenience.

I found the error, the database connection was not correct.

But thank you very much for answering.

**Comment by hamishwillee** [comment]
Thanks for letting me know! Glad you were able to get this working.
