### ISSUE TITLE
Error in Pug template book_delete.pug

### ISSUE THREAD

**Issue by nitramrelpmur** [mdn/express-locallibrary-tutorial#128]
Before posting an issue, please confirm:
- [X] Issue can be reproduced on THIS repository (setup using [quickstart instructions](https://github.com/mdn/express-locallibrary-tutorial#quick-start)).
- [X] I am using a clean/fresh database
- [X] I have provided output logs and information about my environment setup below.

There is an error in the Pug template `book_delete.pug`. The book instances are displayed within a h4 tag (see screenshot).
The problem is the additional indentation for the each-in loop after the tag `h4 Copies` 

![Screenshot 2022-01-04 at 12-39-52 Delete Book](https://user-images.githubusercontent.com/15095591/148054070-96779403-b00f-41e9-bc6c-2ddf06c85019.png)

**Comment by hamishwillee** [comment]
Thanks very much! Fixed.
