### ISSUE TITLE
first try

### ISSUE THREAD

**Issue by kingbeezyx** [mdn/express-locallibrary-tutorial#130]
Before posting an issue, please confirm:
- [ ] Issue can be reproduced on THIS repository (setup using [quickstart instructions](https://github.com/mdn/express-locallibrary-tutorial#quick-start)).
- [ ] I am using a clean/fresh database
- [ ] I have provided output logs and information about my environment setup below.

**Comment by hamishwillee** [comment]
Please don't create empty issues.
