### ISSUE TITLE
MongoDB database instance to use for auth branch?

### ISSUE THREAD

**Issue by blobtub** [mdn/express-locallibrary-tutorial#137]
Which pre-set MongoDB connection URL supports running the version of this tutorial that's on the "auth" branch?

Using the `mongodb://******:******@ds119748.mlab.com:19748/local_library` connection URL throws an ENOTFOUND error<sup>[1]</sup>.  Using the connection URL from the current "main" branch (as of 2022-12-05, `mongodb+srv://******:******@cluster0.a9azn.mongodb.net/local_library`) throws a different error:

_Error [MongoError]: (Unauthorized) not authorized on admin to execute command { insert: "system.indexes", documents: [[{ns admin.sessions} {key [{expires 1}]} {name expires_1} {expireAfterSeconds 0} {unique false}]], ordered: true }_

If neither of the above MongoDB instances can support running the "auth" code, would someone need to diverge very much from the guide at https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#setting_up_the_mongodb_database to get one working for auth?

<br>

[1] _Error [MongoError]: failed to connect to server [ds119748.mlab.com:19748] on first connect [Error: getaddrinfo ENOTFOUND ds119748.mlab.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)_

**Comment by hamishwillee** [comment]
Closing. This question is out of scope - it's not an error in the docs but something that you want to do that exceeds what the documentation allows.

I'd answer it if I knew, but I haven't done the necessary investigation. This might be a better question for stackoverflow.

**Comment by blobtub** [comment]
Done.
https://stackoverflow.com/questions/74695876/mongodb-database-instance-to-use-for-auth-branch-of-mdn-local-library-express @caglarturali #54
