### ISSUE TITLE
Confusion regarding the Part 6: Working with forms

### ISSUE THREAD

**Issue by BatuhanBudak** [mdn/express-locallibrary-tutorial#154]
### Before submitting the issue, check you have done the following:

- [X] Issue can be reproduced on this repository following [quick-start instructions](https://github.com/mdn/express-locallibrary-tutorial#quick-start).
- [X] I am using a clean/fresh database
- [X] I have included output logs and information about my environment setup below.

### What was incorrect, unhelpful, or unexpected?

I'm currently on Part 6: Working with forms of the tutorial and I've completed the sixth sub-article of this section. In the view section of this lesson, there is an instruction that states we should add the following code to book_form.pug template.

`option(
              value=author._id
              selected=(
                author._id.toString()==book.author._id
                || author._id.toString()==book.author
              ) ? 'selected' : false
            ) #{author.name}`

However, when I inspect the code from the repository I see the following line of code:

` option(value=author._id selected=(author._id.toString()===book.author._id.toString() ? 'selected' : false) ) #{author.name}`

Which is the old state of the code before the change to book_form view template in this lesson. I've checked both code blocks and both of them seem to work. 

So this left me wondering if the below-mentioned statement regarding this change from the same lesson is redundant.

> This code change is required so that the book_form can be used for both creating and updating book objects (without this, there is an error on the GET route when creating a form)

Which source should be followed? 

.

### What did you expect to see?

Settling differences between the tutorial and the code base.

**Comment by hamishwillee** [comment]
Thanks - you're right. I can't find out why/how the worked project and the docs got out of sync, but the original view works fine and is much easier to understand. I have therefore removed the section from the "update" doc. Should be fixed when https://github.com/mdn/content/pull/23852 gets merged.
