### ISSUE TITLE
express command does not work in git bash

### ISSUE THREAD

**Issue by RemeAjayi** [mdn/express-locallibrary-tutorial#2]
Hello, I was trying to follow the local library tutorial and after installing express and running 
npm install express-generator -g
All is well, but as soon as I try typing express, git bash gives me "command not found".

**Comment by chrisdavidmills** [comment]
Hi there!

So I take it you've followed the installation instructions at:

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/development_environment

?

Did you definitely install Node/NPM latest version, then install express with "npm install express-generator -g", then try to use it?

Which operating system are you on? I'm assuming Windows, as you are talking about the git bash.

Have you tried running it all through the regular command line?

**Comment by RemeAjayi** [comment]
Hello,
Thank you for your reply. I am using git bash and I also tried using the Windows command prompt, but it said express is not recognized as an external or internal command. 
However, I downloaded webstorm which has the generator pre-installed. I am currently on the database tutorial.
Regards, 
Reme.

-----Original Message-----

**Comment by chrisdavidmills** [comment]
Ah, cool, so you are sorted. 

It probably had something to do with the express command not being available in your PATH variable, although I'm sure using the -g flag when installing sorts that out for you.

It sounds like WebStorm did a better job of sorting that out ;-)

**Comment by RemeAjayi** [comment]
Good day Sir,
I was able to complete the mozilla local library tutorial(though I am yet
to host it). I was trying to apply the principles for my own blogging
application. However, I am getting this error.
Mongo DB connectionerror: {[MongoError: connection 0 to
ds155841.mlab.com:55841 timed out'}
Please, I would appreciate any help.

**Comment by hamishwillee** [comment]
@RemeAjayi This is a mongoose/mongodb issue - not one with this example. Suggest you try google, which shows up issues like: https://github.com/Automattic/mongoose/issues/4789
