### ISSUE TITLE
Update express-validator legacy Api to v4

### ISSUE THREAD

**Issue by VaibhavAjayGupta** [mdn/express-locallibrary-tutorial#23]
express-validator legacy Api is depreciated and it's recommended not to use in new projects.

**Comment by hamishwillee** [comment]
The breaking changes as per [Upgrade guide](https://github.com/ctavan/express-validator/blob/master/UPGRADE_GUIDE.md) are fixed. I'll look at the API now. Thanks! 

@VaibhavAjayGupta Do you think you'd be OK to review the PR when it is done?

**Comment by VaibhavAjayGupta** [comment]
Sure thing.

**Comment by hamishwillee** [comment]
This addressed by https://github.com/mdn/express-locallibrary-tutorial/pull/25 and https://github.com/mdn/express-locallibrary-tutorial/pull/28/files

**Comment by hamishwillee** [comment]
This is all done now - thanks @VaibhavAjayGupta ! I've also updated the documentation.

**Comment by VaibhavAjayGupta** [comment]
Thank you for updating and awesome documentation.

**Comment by hamishwillee** [comment]
:-)
