### ISSUE TITLE
 ./models/genre.js file

### ISSUE THREAD

**Issue by GHNewbiee** [mdn/express-locallibrary-tutorial#3]
As per instruction: _This name should be required and have between 3 and 100 characters._

**min** **max** properties are missing from the model.

**Comment by chrisdavidmills** [comment]
Yup, you are right about this. I've updated the model - see 

https://github.com/mdn/express-locallibrary-tutorial/blob/master/models/genre.js

Does this look good? Also adding @hamishwillee here, just so he can verify.

**Comment by hamishwillee** [comment]
Looks right to me - thanks for reporting that @GHNewbiee  - and @chrisdavidmills  for fixing it.
