### ISSUE TITLE
/controllers/authorController.js.

### ISSUE THREAD

**Issue by GHNewbiee** [mdn/express-locallibrary-tutorial#4]
In file, line 26:
`authors_books: function(callback) {...`
changes to
`author_books: function(callback) {...`

Also, in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data line: 9

PS: Thanks for the great tutorial!

**Comment by chrisdavidmills** [comment]
Thanks for the comment, and sorry we missed it for so long.

@hamishwillee can you give this a quick check over? I recall the code working as is, and don't think the author/authors thing is a problem - it part of the naming convention, right?

I could be wrong; it's been ages since I looked at this.

**Comment by hamishwillee** [comment]
@GHNewbiee This is not a defect. Let me explain. The entire function is shown below:
```javascript
// Display detail page for a specific Author
exports.author_detail = function(req, res, next) {

    async.parallel({
        author: function(callback) {
            Author.findById(req.params.id)
              .exec(callback)
        },
        authors_books: function(callback) {
          Book.find({ 'author': req.params.id },'title summary')
          .exec(callback)
        },
    }, function(err, results) {
        if (err) { return next(err); }
        //Successful, so render

        res.render('author_detail', { title: 'Author Detail', author: results.author, author_books: results.authors_books } );
    });
};
```
What is happening is that `async_parallel` is taking an object that contains a number of named (callback) functions. The `async_parallel` completes with a callback that contains another object that has attributes with the same names as the functions passed into the original object, each which contain the results of those callback. 

The last part takes assigns the returned value (`results.authors_books`) to the template value that will be rendered (`author_books`)
```
        res.render('author_detail', { title: 'Author Detail', author: results.author, author_books: results.authors_books } );
```

The point here is that the functions in the object passed to `async.parallel` can be can be named anything. The important thing is that they are mapped to the name of the variable used in the template.  In this case I have chosen to make them slightly different to make it easier to see that they are different. 

Hope that makes sense. Really appreciate you taking the time to help us spot errors in this content!
