### ISSUE TITLE
Error when trying to create home page

### ISSUE THREAD

**Issue by justinbansal** [mdn/express-locallibrary-tutorial#45]
When using this code in BookController.js the home page stops loading:

exports.index = function(req, res) {

    async.parallel({
        book_count: function(callback) {
            Book.count(callback);
        },
        book_instance_count: function(callback) {
            BookInstance.count(callback);
        },
        book_instance_available_count: function(callback) {
            BookInstance.count({status:'Available'},callback);
        },
        author_count: function(callback) {
            Author.count(callback);
        },
        genre_count: function(callback) {
            Genre.count(callback);
        },
    }, function(err, results) {
        res.render('index', { title: 'Local Library Home', error: err, data: results });
    });
};

Console doesn't say anything
all I get is GET/catalog/ -- ms - -

And the localhost:3000 page is just stuck in loading state

**Comment by justinbansal** [comment]
I think this code is a problem for me...

 // book_count: function(callback) {
        //     Book.count(callback);
        // }
        // book_instance_count: function(callback) {
        //     BookInstance.count(callback);
        // },
        // book_instance_available_count: function(callback) {
        //     BookInstance.count({status:'Available'},callback);
        // },
        // author_count: function(callback) {
        //     Author.count(callback);
        // },
        // genre_count: function(callback) {
        //     Genre.count(callback);
        // },

**Comment by justinbansal** [comment]
This is also an issue in BookController.js

// Display list of all books.
exports.book_list = function(req, res, next) {

    Book.find({}, 'title author ')
      .populate('author')
      .exec(function (err, list_books) {
        if (err) { return next(err); }
        // Successful, so render
        res.render('book_list', { title: 'Book List', book_list:  list_books});
      });
  
  };

**Comment by justinbansal** [comment]
I was missing mongodb:// before my db URL which was causing these issues to occur.

**Comment by hamishwillee** [comment]
Phew!

**Comment by JegadeeshVontlin** [comment]
@justinbansal  Hey bro, How can you change the code to localhost(because it is fetching data from mongodb server via populate js), am also in the same problem. console doesn't return anything and index page is in loading state.

**Comment by part1zon** [comment]
> @justinbansal Hey bro, How can you change the code to localhost(because it is fetching data from mongodb server via populate js), am also in the same problem. console doesn't return anything and index page is in loading state.

in my case i created mongoDB in wrong URL (********-imbyo.gcp.mongodb.net/**test**?retryWrites=true&w=majority). test =>local_library
now its working OK
