### ISSUE TITLE
nested categories

### ISSUE THREAD

**Issue by sorokinvj** [mdn/express-locallibrary-tutorial#46]
Hi, 

I would like to use your model as a starting point for my app. However, in my requirements there are nested categories, so if you don't mind I would ask how to implement those? For example, if your Genre would be much more complex like 

→ Science Fiction
→→  AI
→→→ War
→→ Cosmos  
→→→ Interracial contact 

then how do you change your model?

**Comment by hamishwillee** [comment]
Having not tried it, I couldn't say "for sure". What I would look at though is adding a field "parent" for each Genre of the type Genre. Ie
```
var GenreSchema = new Schema(
  {
 parent: { type: Schema.ObjectId, ref: 'Genre', required: false },
 ...
```
A Genre could then have at most one parent. You could generate the child lists using the techniques described in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

I suspect there would be complications, but that might be enough to get started.

**Comment by sorokinvj** [comment]
Thanks a lot!
