### ISSUE TITLE
Use of req.params.id in book_delete_post()

### ISSUE THREAD

**Issue by dhollinden** [mdn/express-locallibrary-tutorial#48]
Hello, 

In the book_delete_post() method of bookController.js, there are two cases where req.params.id is used:

Book.findById(req.params.id)

BookInstance.find({ 'book': req.params.id })

It seems to me these should both use: req.body.id

I believe the method works "as is" because the Delete button is never displayed if any book instances exist, so it doesn't matter if the Book.find and BookInstance.find fail. 

Looking forward to your response. 

Dave

**Comment by hamishwillee** [comment]
The two calls don't depend on whether the delete button exists or if there are any book instances. In fact they will succeed as long as the id is of the correct format.
```
Book.findById(req.params.id)
BookInstance.find({ 'book': req.params.id })
```
As the forms are only displayed if you have the correctly formatted URL, and that includes a param for the id this should always work *in normal use*. You can of course break it by not including the ID in the URL or having and badly structured ID.

It would be *better* if the id was passed in the request body  (generally any field that changes the database should come through the form to reduce certain times of attack) but this should still work.

**Comment by hamishwillee** [comment]
PS Try it, it works.

**Comment by dhollinden** [comment]
Thanks for your response! The id IS passed to book_delete_post() in the request body. That's why Book.findById and BookInstance.find should be using req.body.id.

Let me state it like this, by analogy

**database calls in author_delete_post() method:**

Author.findById(req.body.authorid)
Book.find({ 'author': req.body.authorid })
Author.findByIdAndRemove(req.body.authorid

**database calls in book_delete_post() method:**
Book.findById(req.**params**.id)
BookInstance.find({ 'book': req.**params**.id })
Book.findByIdAndRemove(req.body.id

Thanks

**Comment by hamishwillee** [comment]
Thanks very much - I guess it would be better to be consistent. Could you please create a PR and test that it works? If not I will probably do this eventually, but it is not a priority.

**Comment by dhollinden** [comment]
Hello Hamish, 

I'm sorry, I was confused. I was thinking that req.params referred to values on the query string, so it shouldn't be used when processing a POST request. I understand this more clearly now. Sorry for the time spent on your part, but this was a good learning experience for me. 

Best, 

Dave

**Comment by hamishwillee** [comment]
@dhollinden No worries. It is a point to question. 

Generally you can use the URL params in both POST and GET requests (because they are there). However it is good practise to only use body parameters for any request that changes the database content - because it is too easy to change the URL, and because you have opportunity to protect against  spoofed forms etc.

Glad you're getting something out of this!
