### ISSUE TITLE
FINAL ERR: ValidationError (part 3 of tutorial)

### ISSUE THREAD

**Issue by rupesh2017** [mdn/express-locallibrary-tutorial#49]
(node:13976) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
FINAL ERR: ValidationError: family_name: Path `family_name` is required., first_name: Path `first_name` is required.

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

**Comment by hamishwillee** [comment]
Thanks!
Fixed the deprecation warning by setting mongoose to use the new parser: `mongoose.connect(mongoDB, { useNewUrlParser: true });`
