### ISSUE TITLE
Populatedb.js never clarified

### ISSUE THREAD

**Issue by LewisVo** [mdn/express-locallibrary-tutorial#5]
In the third tutorial, it is said that 
>  You don't need to know how populatedb.js works at this point. We'll explain the relevant parts in later articles.    

However, it seems that this part is forgotten.

**Comment by chrisdavidmills** [comment]
Good spot. This was a nice-to-have point that the author didn't write as he ran out of time. I've not got time to look into this now, so just for now I've altered the text so it isn't wrong.
