### ISSUE TITLE
Error: Route.get() requires a callback function but got a [object Undefined]

### ISSUE THREAD

**Issue by moonlight729** [mdn/express-locallibrary-tutorial#51]
if use this style will have the title error
router.get('/', book_controller.index);
but if use router.get('/',function () {

});
will ok, how can i do it

**Comment by hamishwillee** [comment]
Sorry to be so late getting back to you. This is not something that can be debugged without the full error trace, but most likely the error woudl occur if the system can't find book_controller.index - ie file not at path you have suggested.

I am closing. Reopen with additional information if you have more debug info.
