### ISSUE TITLE
Stuck in Part 5: Route.get() requires a callback function but got a [object Undefined]

### ISSUE THREAD

**Issue by fatihturan** [mdn/express-locallibrary-tutorial#53]
Hi,

I'm trying to get started with Express JS via MDN. But I stuck in [part 5 / home page section](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page). 

So when I update the `/controllers/bookController.js` file with [sample one](https://gist.github.com/fatihturan/e4a301ec69383dfbd36786f9b9b9541b) I see these errors in terminal:
```
express-locallibrary-tutorial % DEBUG=express-locallibrary-tutorial:* npm run devstart

> express-locallibrary-tutorial@0.0.0 devstart /Users/fatihturan/Desktop/express-locallibrary-tutorial
> nodemon ./bin/www

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
/Users/fatihturan/Desktop/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as get] (/Users/fatihturan/Desktop/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.(anonymous function) [as get] (/Users/fatihturan/Desktop/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/fatihturan/Desktop/express-locallibrary-tutorial/routes/catalog.js:16:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/fatihturan/Desktop/express-locallibrary-tutorial/app.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[nodemon] app crashed - waiting for file changes before starting...`
```

So where I am doing wrong?

**Comment by hamishwillee** [comment]
IMpossible to tell from this. How does your code differ from the vanilla version in this repo?
You might want to upload your whole project to a branch in your own repo in github so it can be tinkered with.

**Comment by fatihturan** [comment]
Sorry @hamishwillee, I've published the current state [on this repo](https://github.com/fatihturan/express-tutorial).

**Comment by hamishwillee** [comment]
Thanks. I can't say how long it will take for me to get to look at this. Probably a few weeks. I suggest you undo as much as possible and work forward until you can more precisely work out the code that is broken.

**Comment by fatihturan** [comment]
@hamishwillee Problem occurring when I change `bookController.js` file from [this one](https://gist.github.com/fatihturan/91c1396ff2dc769be7b4f170f05cfee9) ([Part 4](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes)) to [this version](https://gist.github.com/fatihturan/e4a301ec69383dfbd36786f9b9b9541b) ([Part 5](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page)).

**Comment by caglarturali** [comment]
> @hamishwillee Problem occurring when I change `bookController.js` file from [this one](https://gist.github.com/fatihturan/91c1396ff2dc769be7b4f170f05cfee9) ([Part 4](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes)) to [this version](https://gist.github.com/fatihturan/e4a301ec69383dfbd36786f9b9b9541b) ([Part 5](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page)).

Your `bookController.js` file is missing placeholder controller functions for all the other `/book/` routes. Simply put [this file's contents](https://gist.github.com/fatihturan/91c1396ff2dc769be7b4f170f05cfee9) back in place, and only update where necessary. Do not remove `NOT IMPLEMENTED` controller functions altogether, just update them with provided code :)

**Comment by hamishwillee** [comment]
Thanks @caglarturali - much appreciate your help on this. I'm going to close because the response makes sense.

**Comment by fatihturan** [comment]
@caglarturali Oh, shit. 🤦🏻‍♂️ I guess I didn't pay much attention on part 5 description and I misinterpreted it. Thanks for your replies @hamishwillee @caglarturali. 

Problem solved and I can continue to this tutorial.

**Comment by IkennaVictor** [comment]
Please i am having issue with Part 5: Displaying data. The count returns 0 for all the models when i have some records in my database. It also returns "there is no book" in the book list view. Please help me.
![c](https://user-images.githubusercontent.com/34229262/61978176-744d3080-afe8-11e9-92e4-751f4814c708.JPG)
