### ISSUE TITLE
order of arrays appears random in populatedb.js 

### ISSUE THREAD

**Issue by DJWalker42** [mdn/express-locallibrary-tutorial#61]
The following might be considered pedantic but I thought I'd bring it to your attention.

I've been following the express-locallibrary-tutorial and have got up to Part 5. I used the 'populatedb.js' script to populate a MongoDB on my local machine. I've noticed that the authors, genres and publishers are not in the same as shown in the screen shots. For instance, the "Fantasy" genre in my database has no books in it at all, but the "French Poetry" genre contains the book "The Wise Man's Fear..." plus others I suspect should be in the "Fantasy" genre. There are other "discrepancies" in the publishers and authors.  I think the problem is that the "*Create" functions are called from async.parallel() but use the 'push' method to fill in the global arrays leading to a race condition, and the order of those arrays will be random. For example, "author[0]", which I think the code expects to be the "Patrick Rothfuss" entry is actually whichever call to authorCreate got to the 'push' method first.  As I said this is pedantic but could lead to confusion about the correctness of code. (I at first thought it was a bug with async.parallel() not returning function results in the same order as the functions where declared in the array but on closer inspection I don't think that is the case).

**Comment by hamishwillee** [comment]
Hi @DJWalker42,

You're right - the author and genre create randomly populate the arrays that are then assigned to books - so depending on the system you might get a different assignment. As this was not a "teaching aid" I did not think about that when I wrote it.

What I have done is made the creation of authors/genres happen in series - so they will always be in the same order. This will also fix the assignment for book authors. 

The book instances may not match - that is still done in parallel/random. I'm personally OK with that - I think it far more likely that the books, authors, genres are what people will check. If you felt very strongly about this I could make everything happen in series.

Thanks for pointing this out. Closing now.

**Comment by DJWalker42** [comment]
Hi Hamish,

Thanks for the update. I think the problem I had with it was that approaching this as a novice it appeared as if I'd managed to do something wrong in the code that accessed the MongoDB. It was only when I had eliminated that possibility did I then dive into the database population script where I found the "error".  I think you're right that so long as the book, authors, and genres match that people probably won't check the details of the book instance. You could always leave that as the dreaded "exercise for the reader" task for those who are particularly ambitious (though not really part of the Express-MongoDB  tutorial, its more Javascript only).

Thanks again.

Darren.

________________________________
