### ISSUE TITLE
express-validator breaking behaviour between v5 and v6.

### ISSUE THREAD

**Issue by 0xnoob** [mdn/express-locallibrary-tutorial#69]
[Since version 6](https://github.com/express-validator/express-validator/releases/v6.0.0) of express-validator:

> - Validators and sanitizers will now run in the order they are specified, instead of always running sanitizers first, then validators;

That means, that code like the following will change its behaviour:
```
// Handle Genre create on POST.
exports.genre_create_post =  [
   
  // Validate that the name field is not empty.
  validator.body('name', 'Genre name required').isLength({ min: 1 }).trim(),
```
If you just insert a space as genre-name, this will pass the express-validation, but not the Mongoose one in  [`genre.save`](https://github.com/mdn/express-locallibrary-tutorial/blob/master/controllers/genreController.js#L94):
```
Genre validation failed: name: Path `name` is required.
```

Another change in behavior is by creating a new book and with multiple genres:
By sanitizing with:
` sanitizeBody('*').escape(),`
[bookController.js#L115](https://github.com/mdn/express-locallibrary-tutorial/blob/master/controllers/bookController.js#L115)

it removes every genre but the first one, I think (but not sure) is because of the following breaking change:
> - non-string values will now be sanitized;

---

I am not sure what the best solution is: Always update the express-tutorial to be up to date to the newest versions of the npm-packages it uses or to recommend installing a fixed version?

**Comment by SaltyBuckets** [comment]
creeper

**Comment by hamishwillee** [comment]
@0xnoob Thanks for this - only a year or so late getting back to it :-(

I have updated the example and MDN docs to match the latest express-validator. FYI only this deprecates the sanitiser middleware - you can now use validators for the same purpose. It also does the validators/sanitizers in declaration order - so for the above trim gets called before checking length.

Anyway, both issues and the deprecation are fixed. Much appreciated.
