### ISSUE TITLE
Problem with Part 5

### ISSUE THREAD

**Issue by IkennaVictor** [mdn/express-locallibrary-tutorial#70]
I am getting 0 when trying to display the number of records in the database. Please help me.
![c](https://user-images.githubusercontent.com/34229262/61978748-fc800580-afe9-11e9-8c6e-d1378080bb1d.JPG)

**Comment by hamishwillee** [comment]
Have you added any books to the database?

**Comment by hamishwillee** [comment]
And how does your code differ from the code in this example. How far have you worked through the tutorial?

**Comment by IkennaVictor** [comment]
i have added the sample data from the populatedb.js in the mongodb website. I have checked the codes and i don't see any difference

**Comment by IkennaVictor** [comment]
Even book list does not return any book. Is there a problem with my database? because i followed the tutorial carefully and i have gone back to start again like two more times no difference
![cc](https://user-images.githubusercontent.com/34229262/61992407-dd1ec200-b055-11e9-9190-8dc6773d196c.JPG)

**Comment by IkennaVictor** [comment]
i created a repo in case you want to review my code to see if there's any bug. Please
https://github.com/IkennaVictor/local-library

**Comment by IkennaVictor** [comment]
I tried other models yet I'm still getting the same result. I think i can't get anything from the database and i don't know why. Please help me this is frustrating to me....

**Comment by hamishwillee** [comment]
When you login to mongodb.net do you see the records that you created using populatedb.js? This will help you understand whether the problem is that the records were not created in the first place or there is problem with accessing them. 

If they are created in the database, you might try the original code for this example with your database and see if that works. That then confirms there is something wrong with the code or with the login URL being used.

**Comment by IkennaVictor** [comment]
OH! Thanks I just found out my login url has issues. I didn't replace the test with the name of my database local_library. Thank you @hamishwillee I appreciate!

One more thing, I think you guys should rebuild this tutorial in ES6 and teach us.
Thank once again. I'm grateful. You saved my life, i haven't been myself since yesterday.

**Comment by IkennaVictor** [comment]
OH! Thanks I just found out my login url has issues. I didn't replace the test with the name of my database local_library. Thank you @hamishwillee I appreciate!

One more thing, I think you guys should rebuild this tutorial in ES6 and teach us.
Thank once again. I'm grateful. You saved my life, i haven't been myself since yesterday.
