### ISSUE TITLE
Can't connect to MongoDB database

### ISSUE THREAD

**Issue by IkennaVictor** [mdn/express-locallibrary-tutorial#71]
I am in the stage of deployment to production and decided to test my routes to check that everything still works fine just to fin out that i can no longer connect to database. I logged in to my MongoDB Atlas to see. I found out that my database is gone and trying to create another one is asking me to pay even when i chose the region with free tier.

![mongo err](https://user-images.githubusercontent.com/34229262/62361323-b6a7cd80-b512-11e9-9931-e102f72e5787.JPG)

**Comment by IkennaVictor** [comment]
I just checked again and the database is still there online but i don't know why i'm getting error loading the site in local host

**Comment by SaltyBuckets** [comment]
try making the project all over again

**Comment by javascriptWriter** [comment]
same issue here also

**Comment by javascriptWriter** [comment]
![image](https://user-images.githubusercontent.com/22368311/63268862-38834f00-c2a6-11e9-81fe-89c5b3c710f5.png)

**Comment by chrisdavidmills** [comment]
@hamishwillee can you investigate this one when you get the chance?

**Comment by hamishwillee** [comment]
I just tested this particular repo locally and on heroku using the default database that is coded in. Then deleted database and reuploaded. It all worked fine.

So essentially I know that this project works, and that your code or environment is somehow different.

Most likely you haven't whitelisted your IP address in mongodb. Have you done step 8 in 
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose ?

![image](https://user-images.githubusercontent.com/5368500/63340507-8f625480-c38a-11e9-8228-2d1330873be9.png)

If not, things to  check. 
1. Is your URL in the format here:  https://github.com/mdn/express-locallibrary-tutorial/blob/master/app.js#L19
1. Is your entire connection code like this: https://github.com/mdn/express-locallibrary-tutorial/blob/master/app.js#L19-L24
1. Does this code in this repo work for you using the same versions as defined in package json - https://github.com/mdn/express-locallibrary-tutorial/blob/master/package.json

**Comment by IkennaVictor** [comment]
Thank you! It  worked!
