### ISSUE TITLE
FINAL ERR : ValidationError: genre: Cast to ObjectID failed for value ....

### ISSUE THREAD

**Issue by pavsavov** [mdn/express-locallibrary-tutorial#73]
The following error is being displayed when I run the populatedb.js file from cmd in windows :

`FINAL ERR: ValidationError: genre: Cast to ObjectID failed for value "[ { _id: 5d87dcebde3ec7383840682a, name: 'Fantasy', __v: 0 } ]" at path "genre"
'w' is not recognized as an internal or external command,
operable program or batch file.
`

The genre creation in Db is succesfull. However, if I understand properly, the genres are mapped to authors and that is the moment when the issue manifests.

Any help will be most appreciated. If needed, I could post some more details.

Thanks in advance.

**Comment by hamishwillee** [comment]
I have no idea. I'd probably try copying my genre file into this copy of the project (which I know works) and see if it fails in the same way - then bisect until I find the problem. I think the error basically means invalid id or invalid id object - so either the id it is trying to reference does not exist or you're passing in an object that express has decided is not an id format. 

If you can find the line that causes the problem I might be able to help ... though at that point you will probably be able to work it out yourself.

**Comment by pavsavov** [comment]
Thanks for the tip. I will investigate and will post for future references.

P.S. I copied the genre file from the repository and it dis not helped.After that I decided to write here.

**Comment by aspiringguru** [comment]
I recently worked through the tutorial a couple of times, first attempt reached a point where I was unable to resolve the error. Second time around I found my mistake and better understanding of the tutorial.  I didn't experience a problem with the populatedb.js file.

**Comment by hamishwillee** [comment]
Cheers. Closing.

**Comment by DreamsOfImran** [comment]
I'm getting this same error. Any idea, how to fix this? @aspiringguru @pavsavov
