### ISSUE TITLE
forum for troubleshooting?

### ISSUE THREAD

**Issue by aspiringguru** [mdn/express-locallibrary-tutorial#74]
is there a forum for troubleshooting or a repo for the completed tutorial? (other than stackexchange?)
for that matter, is there a repo with the completed project to compare with.

---------------------------------------------------------------
currently experiencing an error while on the Book_detail_page. probably obvious, thrown me for the moment.

Schema hasn't been registered for model "Genre". Use mongoose.model(name, schema)

my current commit. 

https://github.com/aspiringguru/mdn_express_nodejs_skeleton/tree/c347992765fadebe7af233c0f03ef222cbf4803f

on this page of the tutorial.
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page

**Comment by hamishwillee** [comment]
Yes, this repo is the completed tutorial!

**Comment by aspiringguru** [comment]
obviously I have my wires crossed. I'll dig through to find why my repo is broken.

thanks

**Comment by aspiringguru** [comment]
found my errors. problems were in models/genre.js

change 
  return '/catalog/genreinstance/' + this._id;
to 
  return '/catalog/genre/' + this._id;

change 
module.exports = mongoose.model('GenreInstance', GenreSchema);
to 
module.exports = mongoose.model('Genre', GenreSchema);


yesterday verison of me should have seen this.
