### ISSUE TITLE
minor issues due to current versions of packages.

### ISSUE THREAD

**Issue by aspiringguru** [mdn/express-locallibrary-tutorial#75]
Recently completed the tutorial, minor issues found due to current package versions deprecated methods used in the tutorial. Not essential to use these updates below.

from app.js
```
mongoose.connect(mongoDB, { useUnifiedTopology: true, useNewUrlParser: true, useCreateIndex: true }); 
```

in any of the controllers using express-validator, deprecation errors will result if using 
```
require('express-validator/check'); or require('express-validator/filter');
```

use 
```
require('express-validator'); 
```
instead.

```
const { body,validationResult } = require('express-validator');
const { sanitizeBody } = require('express-validator');
```

**Comment by hamishwillee** [comment]
Thanks for this. First part (`useUnifiedTopology: true, `) fixed in https://github.com/mdn/express-locallibrary-tutorial/pull/97

**Comment by hamishwillee** [comment]
The express validator stuff is fixed by https://github.com/mdn/express-locallibrary-tutorial/pull/100.

Thanks for your help. Closing.
