### ISSUE TITLE
collection.count is deprecated

### ISSUE THREAD

**Issue by ElliottLMz** [mdn/express-locallibrary-tutorial#76]
https://github.com/mdn/express-locallibrary-tutorial/blob/master/controllers/bookController.js (and others)

**Comment by hamishwillee** [comment]
Thanks. Is there a proposed alternative? Love a PR with a fix :-)

**Comment by ElliottLMz** [comment]
I'll see if I can make a PR. Will follow up later.

**Comment by ElliottLMz** [comment]
I've created a PR (#77). Turns out this was only an issue with bookController.index.

**Comment by hamishwillee** [comment]
Awesome!
