### ISSUE TITLE
Where is the Part 3

### ISSUE THREAD

**Issue by TLKG** [mdn/express-locallibrary-tutorial#8]
Guys, do you know where to see source code for [part 3](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose)?
It needs to update and I encountered unhandled rejection error.
Thanks.

**Comment by chrisdavidmills** [comment]
Hi there,

The source code can all be found here: https://github.com/mdn/express-locallibrary-tutorial
