### ISSUE TITLE
Unhandled promise rejection deprecation error when I run populatedb.js (Mongoose/MongoDB section)

### ISSUE THREAD

**Issue by katurian** [mdn/express-locallibrary-tutorial#85]
Hello,

I was following the MongoDB/Mongoose tutorial, when I hit an error in this [section](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#Testing_%E2%80%94_create_some_items). I installed async with npm and downloaded [populatedb.js](https://raw.githubusercontent.com/mdn/express-locallibrary-tutorial/master/populatedb.js) from the express-locallibrary-tutorial repository. With populatedb.js at the same directory level as package.json, I ran the following command from **CMD on Windows 10**:

 ```
node populatedb mongodb+srv://'username':'password'@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true
```

Here are some of the error messages I received:

```

(node:16032) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine,
pass option { useUnifiedTopology: true } to the MongoClient constructor.

(node:16032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a prom
ise which was not handled with .catch(). (rejection id: 1)

(node:16032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-z
ero exit code.


```
Does populatedb.js need to be updated or do I need to install an earlier version of Node? My current version is **12.13.0**.

Thanks.

**Comment by hamishwillee** [comment]
Hi,
I can't keep up with node (or any changes really) so the example expects the environment in https://github.com/mdn/express-locallibrary-tutorial/blob/master/package.json

Can you try that environment. At least then you'll know if the problem is node version or not.

**Comment by tyqi11** [comment]
Hi, 

The error message tells to pass the option useUnifiedTopology. In this case, it should be on line 22:
 https://github.com/mdn/express-locallibrary-tutorial/blob/f805c565813d29c10d41348d79286a09d372ff06/populatedb.js#L22

change it to: `mongoose.connect(mongoDB, { useNewUrlParser: true, newUnifiedTopology: true });`

Hope this helps.

**Comment by hamishwillee** [comment]
Thanks @tyqi11 .

FWIW the tutorial works against a set of dependencies as listed in the package.json. As time goes by if you just get the latest set of dependencies things change and the instructions no longer work. We try to update periodically, but no guarantees.
I'm going to leave this open because at some point we'll update, and having this information will be useful.

**Comment by hamishwillee** [comment]
It was useful :-). Fixed this in https://github.com/mdn/express-locallibrary-tutorial/pull/97
