### ISSUE TITLE
 npm run serverstart not working on Windows

### ISSUE THREAD

**Issue by Wildvuur** [mdn/express-locallibrary-tutorial#87]
i am following the tutorial but i get errors when i try npm run serverstart.

when i change 
```
  "scripts": {
    "start": "node ./bin/www",
    "devstart": "nodemon ./bin/www",
    "serverstart": "DEBUG=express-locallibrary-tutorial:* npm run devstart"
  }, 
```
with 
```
  "scripts": {
    "start": "node ./bin/www",
    "devstart": "nodemon ./bin/www",
    "serverstart": "set DEBUG=express-locallibrary-tutorial:* | npm run devstart"
  },
```
and run 
`npm run serverstart`
then i get no errors but i dont know if this is correct

**Comment by hamishwillee** [comment]
No, the line is wrong. See instructions for windows in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website
