### ISSUE TITLE
What's the use of the callbacks in async.parallel member functions ?

### ISSUE THREAD

**Issue by kansalabhishek** [mdn/express-locallibrary-tutorial#92]
So, I understand that when you have multiple functions that need to be called asynchronously, we use async.parallel and pass an array or object of functions. 

But inside these functions( inside the object of functions), a 'callback' argument is passed and then just passed to exec function.

What is this 'callback' argument ? Where does it come from ? How is it necessary ?

[mdn reference](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Genre_detail_page)

``` javascript
// Display detail page for a specific Genre.
exports.genre_detail = function(req, res, next) {

    async.parallel({
        genre: function(callback) {
            Genre.findById(req.params.id)
              .exec(callback);
        },

        genre_books: function(callback) {
            Book.find({ 'genre': req.params.id })
              .exec(callback);
        },

    }, function(err, results) {
        if (err) { return next(err); }
        if (results.genre==null) { // No results.
            var err = new Error('Genre not found');
            err.status = 404;
            return next(err);
        }
        // Successful, so render
        res.render('genre_detail', { title: 'Genre Detail', genre: results.genre, genre_books: results.genre_books } );
    });

};
```

**Comment by hamishwillee** [comment]
Read https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/flow_control_using_async "Asynchronous operations in parallel"

This is passed in to each function which uses it to return a result or an error. The framework can then use the result or error to handle the failure.
