### ISSUE TITLE
Able to insert new author even though have not setup mongodb atlas

### ISSUE THREAD

**Issue by 000orion000** [mdn/express-locallibrary-tutorial#95]
Hi,

I have clone it and running it in Digital Ocean.
I am a bit puzzled that I am able to insert new authors despite
not setting up the connection to atlas.

 The code I am referring to is in app.js -
`var dev_db_url = 'mongodb+srv://cooluser:coolpassword@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true'
`

Thanks in advance...

**Comment by hamishwillee** [comment]
See the following lines:
```
var dev_db_url = 'mongodb+srv://cooluser:coolpassword@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true'
var mongoDB = process.env.MONGODB_URI || dev_db_url;
mongoose.connect(mongoDB, { useNewUrlParser: true });
```
Mongoose connects through to that database by default.

Hope that answers your question.
